<?php

	$contact_name = $_POST['name'];
	$contact_email = $_POST['email'];
	$contact_subject = $_POST['subject'];
	$contact_message = $_POST['message'];
	
	$err_occured=0;
	$flag_emailid=0;
	$flag_incomplete=0;
	$flag_mailerror=0;
	$flag_success=0;
	
	//check if all data present
	if($contact_name=='' || $contact_email=='' || $contact_subject=='' || $contact_message=='') 
	{
		$flag_incomplete=1;
		$err_occured=1;
	}
	//validate legal emailid
	if (!filter_var($contact_email, FILTER_VALIDATE_EMAIL))
	{
		$flag_emailid=1;
		$err_occured=1;
	}
	
	if($err_occured==0)
	{
		$sender = $contact_email;
		$receiver = "mail@sristi.org.in";
		$client_ip = $_SERVER['REMOTE_ADDR'];
		$email_body = "Name: " . $contact_name . "\nEmail: " . $sender . " \n\nSubject: " . $contact_subject . " \n\nMessage: \n\n" . $contact_message . " \n\nIP: " . $client_ip . "\n\nAutomated email generated by www.sristi.org.in.";		
		$extra = "From: " . $sender . "\r\n" . "Reply-To: " . $sender . "\r\n" . "X-Mailer: PHP/" . phpversion();
		
		$email_body_auto_reply = "Hello " . $contact_name . ", \nThis is the auto reply message. Thank you. \n\nAdmin - www.sristi.org.in";
		$extra_auto_reply = "From: " . $receiver . "\r\nReply-To: " . $receiver . "\r\n" . "X-Mailer: PHP/" . phpversion();
		
		mail( $sender, "Sristi '11 Contact Us Form - Auto Reply - Re: " . $contact_subject, $email_body_auto_reply, $extra_auto_reply );
	
		if( mail( $receiver, "Sristi '11 Contact Us Form - " . $contact_subject, $email_body, $extra ) ) 
		{
			$flag_success=1;
		}
		else
		{
			$err_occured=1;
			$flag_mailerror=1;
		}
	}
	
	//feedback to user	
	$err_string="location:sristi-contactus.php?r=";
	if($flag_incomplete==1)
	{
		$err_string=$err_string . "incomplete";
	}
	else if($flag_emailid==1)
	{
		$err_string=$err_string . "invalidemail";
	}
	else if($flag_mailerror==1)
	{
		$err_string=$err_string . "mailerror";
	}
	else
	{
		$err_string=$err_string . "success";
	}
	header($err_string . "#fdbck");
	
?>